server:
  port: 11101
  # 接口统一前缀
  servlet:
    context-path: /blb

version: '1.0.0'

spring:
  application:
    name: 'bbb_lbb'
  profiles:
    active: dev
  datasource:
    druid:
      # 初始化 最小 最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      filters: stat,wall
      filter:
        stat:
          enabled: true
          db-type: mysql
          # 开启慢sql监控
          log-slow-sql: true
          # 慢sql超时毫秒
          slow-sql-millis: 5000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.thy.**.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

jasypt:
  encryptor:
    password: "THY-bbb_lbb@24"
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
