spring:
  datasource:
    druid:
      # 是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
      # 根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html
      # http://loacalhsot:8081/druid
      stat-view-servlet:
        # 是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        enabled: true
        url-pattern: '/druid/*'
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username:
        # 登录密码
        login-password:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.109.80.139:3306/bbb_lbb_main?useSSL=false&serverTimezone=UTC
          username: thy
          password: ENC(xD/s6lzV3b0SLKA7aaqWTHI6ls8wVzYx)

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.thy: DEBUG
  file:
    name: log/dev.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{50} : %line] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{50} : %line] - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 31
      total-size-cap: 100MB
      file-name-pattern: log/dev.%d{yyyy-MM-dd}.%i.log
